import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  authContainer: {
    flex: 1,
    backgroundColor: '#05070f',
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  logo: {
    color: '#e50914',
    fontWeight: '800',
    fontSize: 22,
  },
  curtainSection: {
    marginTop: 16,
    gap: 12,
  },
  curtainStage: {
    height: 320,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#060910',
    position: 'relative',
  },
  curtainStageTall: {
    height: 440,
  },
  curtainPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    overflow: 'hidden',
  },
  curtainPanelLeft: {
    left: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  curtainPanelRight: {
    right: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  curtainStripes: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 6,
    gap: 4,
  },
  curtainStripe: {
    flex: 1,
    borderRadius: 6,
  },
  curtainFill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 0,
  },
  curtainSheen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 0,
  },
  curtainContent: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: 12,
    bottom: 12,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },
  curtainButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  curtainButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    backgroundColor: '#0b1021',
  },
  curtainButtonPrimary: {
    backgroundColor: '#e50914',
    borderColor: '#e50914',
  },
  curtainButtonText: {
    fontWeight: '700',
  },
  curtainButtonPrimaryText: {
    fontWeight: '700',
    color: '#fff',
  },
  authCard: {
    marginTop: 12,
    backgroundColor: '#0b1021',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#111827',
  },
  authTabs: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  authTab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  authTabActive: {
    backgroundColor: '#e50914',
    borderColor: '#e50914',
  },
  authTabText: {
    color: '#fff',
    fontWeight: '700',
    letterSpacing: 1,
  },
  authTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 12,
  },
  input: {
    backgroundColor: '#0f172a',
    color: '#fff',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  primaryButton: {
    backgroundColor: '#e50914',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 6,
  },
  primaryText: {
    color: '#fff',
    fontWeight: '700',
  },
  providerButton: {
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    marginTop: 10,
  },
  providerText: {
    fontWeight: '700',
  },
  homeContainer: {
    flex: 1,
    backgroundColor: '#05070f',
  },
  navBar: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLinks: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  navLink: {
    color: '#e5e7eb',
    fontSize: 12,
    letterSpacing: 1,
  },
  navActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  logoutPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1f2937',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#0b1021',
  },
  logoutPillText: {
    color: '#cbd5e1',
    fontWeight: '600',
  },
  menuButton: {
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 12,
  },
  navDropdown: {
    position: 'absolute',
    top: 64,
    left: 0,
    right: 0,
    minHeight: 200,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 16 },
    elevation: 16,
    zIndex: 10,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  navRow: {
    paddingVertical: 10,
    marginBottom: 10,
  },
  hero: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 6,
  },
  heroEyebrow: {
    color: '#9ca3af',
    letterSpacing: 2,
    fontSize: 11,
  },
  heroTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#cbd5e1',
    fontSize: 13,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#0f172a',
    color: '#fff',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  searchHint: {
    marginTop: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  searchHintText: {
    color: '#e50914',
    fontWeight: '700',
    textAlign: 'center',
  },
  sortSection: {
    marginTop: 14,
  },
  sortLabel: {
    fontWeight: '700',
    marginBottom: 8,
  },
  sortRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sortChip: {
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#0b1021',
  },
  sortChipText: {
    fontWeight: '700',
  },
  filterSection: {
    marginTop: 18,
    gap: 12,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  filterGroup: {
    flex: 1,
    minWidth: '30%',
  },
  filterLabel: {
    fontWeight: '700',
    marginBottom: 6,
  },
  filterSelect: {
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: '#0b1021',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterSelectText: {
    fontWeight: '700',
  },
  filterCaret: {
    fontWeight: '700',
    marginLeft: 8,
  },
  filterDropdown: {
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 8,
    overflow: 'hidden',
  },
  filterOption: {
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  filterOptionText: {
    fontWeight: '600',
  },
  filterReset: {
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  filterResetText: {
    fontWeight: '800',
    color: '#fff',
  },
  secondaryButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1f2937',
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#0b1021',
  },
  secondaryText: {
    color: '#e5e7eb',
    fontWeight: '700',
  },
  heroButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  noteBubble: {
    marginTop: 10,
    backgroundColor: '#0f172a',
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  noteBubbleText: {
    color: '#e5e7eb',
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 4,
  },
  sectionTitle: {
    color: '#e5e7eb',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  card: {
    backgroundColor: '#0b1021',
    borderRadius: 12,
    padding: 10,
    marginRight: 12,
    width: 109,
    borderWidth: 1,
    borderColor: '#1f2937',
    position: 'relative',
  },
  poster: {
    height: 128,
    borderRadius: 8,
    backgroundColor: '#111827',
    marginBottom: 10,
    zIndex: 1,
  },
  sliderArrows: {
    position: 'absolute',
    top: '40%',
    left: -20,
    right: -20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    pointerEvents: 'box-none',
  },
  sliderArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    color: '#fff',
    fontWeight: '700',
    marginBottom: 4,
  },
  cardTag: {
    color: '#9ca3af',
    fontSize: 12,
    marginBottom: 10,
  },
  wishButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1f2937',
    paddingVertical: 8,
    alignItems: 'center',
    backgroundColor: '#0f172a',
  },
  wishButtonActive: {
    borderColor: '#e50914',
    backgroundColor: 'rgba(229,9,20,0.12)',
  },
  wishButtonText: {
    color: '#e5e7eb',
    fontWeight: '700',
    fontSize: 12,
  },
  wishHeart: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f2937',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    zIndex: 3,
  },
  wishHeartActive: {
    backgroundColor: '#e50914',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
  },
  modalCard: {
    width: '80%',
    maxWidth: 320,
    backgroundColor: '#0b1021',
    padding: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1f2937',
    gap: 12,
  },
  modalTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
  },
  modalText: {
    color: '#cbd5e1',
    fontSize: 14,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1f2937',
    backgroundColor: '#0f172a',
  },
  modalButtonPrimary: {
    backgroundColor: '#e50914',
    borderColor: '#e50914',
  },
  popularCard: {
    flexDirection: 'row',
    gap: 10,
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
  },
  popularPoster: {
    width: 100,
    height: 150,
    borderRadius: 8,
    backgroundColor: '#111827',
    position: 'relative',
    zIndex: 1,
  },
  popularBody: {
    flex: 1,
    paddingRight: 50,
    minHeight: 150,
    maxHeight: 150,
    justifyContent: 'flex-start',
    gap: 4,
  },
})
