// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgAsTi5gpu1bFpXGi1TVQ2cWq2mSMS0rw',
    appId: '1:309869010872:android:d36d817eb1e31dca46f94d',
    messagingSenderId: '309869010872',
    projectId: 'pb-team',
    storageBucket: 'pb-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkSRKJdVs9jA6Cb7AKcsguH75ZEGzHj4',
    appId: '1:309869010872:ios:d069b1cdea35b85046f94d',
    messagingSenderId: '309869010872',
    projectId: 'pb-team',
    storageBucket: 'pb-team.firebasestorage.app',
    androidClientId: '309869010872-di41gfk86ko8h76b6s3qusqsf44j31po.apps.googleusercontent.com',
    iosClientId: '309869010872-bhnn27ea4coh4t56q1df737i6amds9bl.apps.googleusercontent.com',
    iosBundleId: 'com.pbteam.app',
  );
}
